version: '3'
services: 
  bot:
    build: .
    env_file: .env
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes: 
  db:
    driver: local
