CREATE TYPE public."challengestatus" AS ENUM
    ('PND', 'BET', 'DEC', 'CMP');

ALTER TYPE public."challengestatus"
    OWNER TO "hammy";

CREATE TABLE public."challenges"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 ),
    "ChallengerId" text NOT NULL,
    "ChallengedId" text NOT NULL,
    "ChannelId" text NOT NULL,
    "StatusMessageId" text,
    "Description" text NOT NULL,
    "Status" "challengestatus" NOT NULL,
    "BetLimit" bigint,
    "ChallengerBet" bigint,
    "ChallengedBet" bigint,
    "WinnerId" text,
    "CreationTimestamp" timestamp with time zone NOT NULL DEFAULT now(),
    "CompletedTimestamp" timestamp with time zone,
    CONSTRAINT "PRIMARY_KEY" PRIMARY KEY ("Id")
)
WITH (
    OIDS = FALSE
);

ALTER TABLE public."challenges"
    OWNER to "hammy";

CREATE TABLE public.dad_of_month
(
    "Id"         integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 ),
    "GuildId"    text NOT NULL,
    "UserId"     text NOT NULL,
    "Year"       integer NOT NULL,
    "Month"      integer NOT NULL,
    "IsOverride" boolean NOT NULL DEFAULT FALSE,
    "CreatedAt"  timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "dad_of_month_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "dad_of_month_guild_year_month_unique" UNIQUE ("GuildId", "Year", "Month")
)
WITH (
    OIDS = FALSE
);

ALTER TABLE public.dad_of_month
    OWNER to "hammy";