-- Baseline schema: the WATO challenges table that previously lived in init.sql.
-- Guarded with IF NOT EXISTS / a duplicate_object catch so this migration is a
-- safe no-op on databases that were already provisioned from the old init.sql.
-- Ownership is not set here: migrate connects as POSTGRES_USER, so it owns
-- everything it creates.

DO $$ BEGIN
    CREATE TYPE public."challengestatus" AS ENUM ('PND', 'BET', 'DEC', 'CMP');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS public."challenges"
(
    "Id"                 integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 ),
    "ChallengerId"       text NOT NULL,
    "ChallengedId"       text NOT NULL,
    "ChannelId"          text NOT NULL,
    "StatusMessageId"    text,
    "Description"        text NOT NULL,
    "Status"             "challengestatus" NOT NULL,
    "BetLimit"           bigint,
    "ChallengerBet"      bigint,
    "ChallengedBet"      bigint,
    "WinnerId"           text,
    "CreationTimestamp"  timestamp with time zone NOT NULL DEFAULT now(),
    "CompletedTimestamp" timestamp with time zone,
    CONSTRAINT "PRIMARY_KEY" PRIMARY KEY ("Id")
);
