-- Dad of the Month feature table. Uses IF NOT EXISTS so it is safe even if the
-- table was hand-created on a database before migrations were introduced.

CREATE TABLE IF NOT EXISTS public.dad_of_month
(
    "Id"         integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 ),
    "GuildId"    text NOT NULL,
    "UserId"     text NOT NULL,
    "Year"       integer NOT NULL,
    "Month"      integer NOT NULL,
    "IsOverride" boolean NOT NULL DEFAULT FALSE,
    "CreatedAt"  timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "dad_of_month_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "dad_of_month_guild_year_month_unique" UNIQUE ("GuildId", "Year", "Month")
);
