name: Go Build

on:
  pull_request:
    branches: [!"main"]
    paths:
      - 'cmd/**'
      - 'internal/**'

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23'

      - name: Build
        run: |
          go build ./... 

#      - name: Run tests
#        run: |
#          go test ./...