on:
    push:
        branches:
            - master
name: Push 'latest' Image to Docker Hub
jobs:
    buildDockerImage:
        name: Build Docker image
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Build Docker image
              env:
                  APPLICATION_NAME: hammy
                  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
              run: docker build -t $DOCKER_USERNAME/$APPLICATION_NAME:latest .
            - name: Docker Login
              env:
                  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
                  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
              run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            - name: Push image to Docker Hub
              env:
                  APPLICATION_NAME: hammy
                  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
              run: docker push $DOCKER_USERNAME/$APPLICATION_NAME:latest
