name: Go Build

on:
  pull_request:
    branches: [!"main"]
    paths:
      - '**/*.go'

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: /tmp/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/*.go') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build
        run: |
          go build ./... 

#      - name: Run tests
#        run: |
#          go test ./...g