name: Build feature image
on:
  push:
    branches-ignore:
      - master
jobs:
  build-feature:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build Docker image
        env:
          APPLICATION_NAME: hammy
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: docker build -t $DOCKER_USERNAME/$APPLICATION_NAME:latest .
