name: Release hammy to droplet
on:
  push:
    tags:
      - v*
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Execute ssh command
        uses: maddox/actions/ssh@master
        env:
          HOST: ${{ secrets.SSH_HOST_IP }}
          USER: ${{ secrets.SSH_USER }}
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          args: |
            docker ps -a
            docker images -a
