name: Release hammy to production
on:
  push:
    tags:
      - v*
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Restart hammy container with latest image
        uses: appleboy/ssh-action@master
        env:
          DISCORD_API_TOKEN: ${{ secrets.DISCORD_API_KEY }}
        with:
          host: ${{ secrets.SSH_HOST_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: DISCORD_API_TOKEN
          script: |
            docker stop hammy
            docker rm hammy
            docker rmi moosebot/hammy
            docker pull moosebot/hammy:latest
            docker run --name hammy --env DISCORD_BOT_TOKEN=$DISCORD_API_TOKEN -d moosebot/hammy:latest
