name: Release hammy to production
on:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Restart hammy container with latest image
        uses: appleboy/ssh-action@master
        env:
          DISCORD_API_TOKEN: ${{ secrets.DISCORD_API_KEY }}
          PGHOST: ${{ secrets.PGHOST }}
          PGUSER: ${{ secrets.PGUSER }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
          PGSCHEMA: ${{ secrets.PGSCHEMA }}
          PGDATABASE: ${{ secrets.PGDATABASE }}
          PGPORT: ${{ secrets.PGPORT }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
        with:
          host: ${{ secrets.SSH_HOST_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: DISCORD_API_TOKEN,PGHOST,PGUSER,PGPASSWORD,PGSCHEMA,PGDATABASE,PGPORT,NODE_ENV
          script: |
            docker stop hammy
            docker rm hammy
            docker rmi moosebot/hammy
            docker pull moosebot/hammy:latest
            docker run --name hammy \
              --env DISCORD_BOT_TOKEN=$DISCORD_API_TOKEN \
              --env PGHOST=$PGHOST \
              --env PGUSER=$PGUSER \
              --env PGPASSWORD=$PGPASSWORD \
              --env PGSCHEMA=$PGSCHEMA \
              --env PGDATABASE=$PGDATABASE \
              --env PGPORT=$PGPORT \
              --env NODE_ENV=$NODE_ENV \
              -d moosebot/hammy:latest
