name: Release hammy to Production Digital Ocean droplet
on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check docker version
        run: docker --version
      - name: Install docker-machine
        run: |
          base=https://github.com/docker/machine/releases/download/v0.16.0 &&
          curl -L $base/docker-machine-$(uname -s)-$(uname -m) >/tmp/docker-machine &&
          sudo mv /tmp/docker-machine /usr/local/bin/docker-machine &&
          chmod +x /usr/local/bin/docker-machine
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v1
        with:
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          public-key: ${{ secrets.SSH_PUBLIC_KEY }}
