name: Release hammy to Production Digital Ocean droplet

on:
  push:
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Check docker version
      run: echo Hello, world!
    - name: Check docker-machine version
      run: docker-machine --version
