name: Release hammy to droplet
on:
  push:
    tags:
      - v*
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Execute ssh command
        uses: maddox/actions/ssh@master
        env:
          HOST: ${{ secrets.SSH_HOST_IP }}
          USER: ${{ secrets.SSH_USER }}
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DISCORD_API_TOKEN: ${{ secrets.DISCORD_API_KEY }}
        with:
          args: |
            docker stop hammy
            docker rm hammy
            docker rmi moosebot/hammy
            docker pull moosebot/hammy:latest
            docker run --name hammy --env DISCORD_BOT_TOKEN=$DISCORD_API_TOKEN -d moosebot/hammy:latest
